--- 
abstract: (EXPERIMENTAL) Common base class for typical REST
author: 
  - J. Shirley, C<< <jshirley at coldhardcode.com> >>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Controller-REST-DBIC-Item
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Action::REST: 0.60
  Catalyst::Action::RenderView: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Runtime: 5.7011
  Catalyst::View::TT: 0
  DBIx::Class: 0
  JSON::DWIW: 0
  JSON::Syck: 0
  SQL::Translator: 0
  YAML: 0
  YAML::Syck: 1.00
version: 0.001000_001
